server-side bug hunt
working out bug causing this error message:
Error: Invalid value for argument: callback Value: undefined

The callback is seemingly defined, so methinks it's another error
closeby.